name: docker

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
    paths-ignore:
    - 'docs/**'
    - 'deploy/**'
    - '*.md'
  pull_request:
    branches:
    - '*'

jobs:

  build:
 
    runs-on: ubuntu-18.04
    # skip commit with "[skip ci]" comment
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
 
    steps:
    - uses: actions/checkout@v2

    - name: Print variables
      run: |
        echo ${{ toJson(github) }}

    - name: Decide on tag
      id: image_tag
      run: |
        tag=$(echo ${{ github.ref }} | sed -e 's/^refs\/heads\///g' -e 's/^refs\/tags\///g' -e 's/^refs\/pull\///g' -e 's/\/merge$//g' | sed -e 's/master/latest/g')
        echo "::set-output name=tag::${tag}"
        echo "::debug::docker image tag ${tag}"
      